### ISSUE TITLE
Error thingy happening again while pulling!

### ISSUE THREAD

**Issue by Ratndeepk** [Ratndeepk/target2months#8]
invalid path '450/Nagendra/greedy/... 
@Nagendracse1 Please look into this. Why this particular program is generating such error.

**Comment by Nagendracse1** [comment]
Delete greedy folder from your local machine- then pull again

**Comment by Ratndeepk** [comment]
not working

**Comment by Nagendracse1** [comment]
send here the full error

**Comment by Ratndeepk** [comment]
![Screenshot 2020-12-17 092325](https://user-images.githubusercontent.com/47817889/102442095-91552a00-4049-11eb-9134-34c6ae6c571f.png)

i think the reason is using * in address

**Comment by Nagendracse1** [comment]
I think you committed after doing some change in your local directory without before pull request.
Do these steps.
git stash
git add --all 
git commit -m " "
git pull
git push

**Comment by Ratndeepk** [comment]
The same error is still happening. & also commiting before pulling doesn't generates any such error instead it just merges. Maybe try renaming the file.

**Comment by Nagendracse1** [comment]
delete whole directry from your machine then again clone it

**Comment by Ratndeepk** [comment]
could you simply rename this file?  same error is occurring "invalid path ...."
